export const ACTION = {
    JOIN: "JOIN",
    JOINED: "JOINED",
    DISCONNECTED: "DISCONNECTED",
    CODE_CHANGE: "CODE_CHANGE",
    REQUEST_SYNC: "REQUEST_SYNC",
    SYNC_CODE: "SYNC_CODE",
    CURSOR_MOVE: 'CURSOR_MOVE',
};
